openapi: 3.1.0
info:
 title: The dog database
 version: 0.0.1
servers:
 - url: http://localhost:3000
paths:
 /dogs:
   get:
      summary: Get all dogs
      operationId: getAllDogs
      responses:
        '200':
          description: A list of dogs
          content:
            application/json:
              schema:
                type: array
                items:
                    items:
                      type: object
                      properties:
                        id:
                          description: The unique index of the dog resource
                          type: string
                        breed:
                          description: The dog's breed
                          type: string
                        color:
                          description: The dog's color
                          type: string
                        weight:
                          description: The dog's weight in kilos
                          type: integer
